<?PHP
	$HEADER="Num_Tabla=$Num_Tabla&Ocampo=$Ocampo&Otipo=$Otipo&B_LIKE=$B_LIKE&T_LIKE=$T_LIKE&OK_LIKE=$OK_LIKE&VINCULOC=$VINCULOC&VINCULOT=$VINCULOT";
	$HEADER.="&DESCRIPCION1=$DESCRIPCION1&Nombre_tabla=$Nombre_tabla&D_tag=$D_tag&NOBANMENU=$NOBANMENU&NBAv=$NBAv&DETENER_AUTOREFRESCO=$DETENER_AUTOREFRESCO";
	$HEADER.="&PAG=$PAG";
?>